---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cybercrime-frontend
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.cybercrime-frontend: glob:master-*
  name: cybercrime-frontend
  namespace: cybercrime-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cybercrime-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cybercrime-frontend
    spec:
      containers:
      - image: gcr.io/report-a-cybercrime-alpha/frontend:master-c416c3c
        imagePullPolicy: Always
        name: cybercrime-frontend
        env:
        - name: PORT
          value: '3000'
        - name: RAZZLE_SERVER_SIDE_API_URI
          value: http://cybercrime-api.cybercrime-api.svc.cluster.local:3000/graphql
        - name: RAZZLE_GOOGLE_ANALYTICS_ID
          value: 'UA-130179934-1'
        resources: {}
        livenessProbe:
          httpGet:
            path: /monitoring/alive
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /monitoring/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
