---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cybercrime-frontend
  annotations:
    flux.weave.works/automated: 'true'
  name: cybercrime-frontend
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cybercrime-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cybercrime-frontend
    spec:
      containers:
      - image: gcr.io/report-a-cyber-crime/frontend:master-8904479
        imagePullPolicy: Always
        name: cybercrime-api
        env:
        - name: PORT
          value: '3000'
        - name: RAZZLE_GOOGLE_ANALYTICS_ID
          valueFrom:
            secretKeyRef:
              key: RAZZLE_GOOGLE_ANALYTICS_ID
              name: frontend-secrets
        resources: {}
        livenessProbe:
          httpGet:
            path: /monitoring/alive
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /monitoring/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
