bases:
- ../../base
patchesStrategicMerge:
- traefik-ingress-controller-deployment.yaml
- traefik-ingress-controller-service.yaml
- cybercrime-api-ingress.yaml
- arango-claim.yaml
- cybercrime-frontend-ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gcr.io/report-a-cybercrime-alpha/frontend
  newTag: master-ae892d2
- name: microsoft/azure-vote-front
  newTag: v2
resources:
- certs-claim.yaml
- azure-storageclass.yaml
