patchesStrategicMerge:
- traefik-ingress-controller-deployment.yaml
- traefik-ingress-controller-service.yaml
- cybercrime-api-ingress.yaml
- arango-claim.yaml
- cybercrime-frontend-ingress.yaml
- minio-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certs-claim.yaml
- azure-storageclass.yaml
- arango-secrets.yaml
- cybercrime-api-secrets.yaml
- minio-secrets.yaml
- flux.yaml
- ../../base
images:
- name: acrrcmpcybercrime.azurecr.io/api
  newTag: master-27336d3a24d64b33bb9a040dee60acf56df26379
- name: acrrcmpcybercrime.azurecr.io/frontend
  newTag: master-89055e755744b3a121e2a4eaf8559c979f5f9330
- name: traefik
  newTag: "1.7"
