patchesStrategicMerge:
- traefik-ingress-controller-deployment.yaml
- traefik-ingress-controller-service.yaml
- cybercrime-api-ingress.yaml
- arango-claim.yaml
- cybercrime-frontend-ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certs-claim.yaml
- azure-storageclass.yaml
- arango-secrets.yaml
- cybercrime-api-secrets.yaml
- minio-secrets.yaml
- ../../base
images:
- name: acrrcmpcybercrime.azurecr.io/api
  newName: gcr.io/report-a-cybercrime-alpha/api
  newTag: master-3a3e8c3
- name: acrrcmpcybercrime.azurecr.io/frontend
  newName: gcr.io/report-a-cybercrime-alpha/frontend
  newTag: master-1034eed
- name: gcr.io/report-a-cybercrime-alpha/frontend
  newTag: master-62e12de
- name: traefik
  newTag: "1.7"
