apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: cybercrime-api
  creationTimestamp: null
  labels:
    app: arangodb
  name: arangodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arangodb
  strategy: {}
  template:
    metadata:
      labels:
        app: arangodb
        name: arangodb
    spec:
      containers:
        - env:
            - name: ARANGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ARANGO_ROOT_PASSWORD
                  name: arango-secrets
          image: arangodb:3.4.1
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 5
            tcpSocket:
              port: 8529
          name: arangodb
          ports:
            - containerPort: 8529
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: 8529
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/arangodb3
              name: arangodb-claim
      restartPolicy: Always
      volumes:
        - name: arangodb-claim
          persistentVolumeClaim:
            claimName: arangodb-claim
status: {}
