name: test_f2

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm run build
        working-directory: f2
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: npm test
        working-directory: f2
        run: npm test
        env:
          CI: true
      - name: npm run lint
        working-directory: f2
        run: npm run lint
        env:
          CI: true
      - name: npm run check-translations
        working-directory: f2
        run: npm run check-translations
        env:
          CI: true
      - name: Run Cypress end-to-end
        working-directory: f2
        run: npm run start:cypress
        env:
          CI: true
